apiVersion: v1
kind: Secret
metadata:
  name: event-processor-secrets
type: Opaque
data:
  SPRING_DATASOURCE_URL: ${DATABASE_URL}
  SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
  SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
  SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
  SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
  SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
  NAMESPACE_APP: ${NAMESPACE_APP}